version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "mvn"
    labels:
      - "chore"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/tailwind"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"
