version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "mvn"
    labels:
      - "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    labels:
      - "chore"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
    labels:
      - "chore"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "terraform"
    labels:
      - "chore"
