services:
  service:
    build:
      context: .
      dockerfile: dev.dockerfile
      args:
        - JAR_FILE=target/*.jar
    ports:
      - 10502:10502
    environment:
      - POSTGRES_DB=l0_auth
      - DOPPLER_TOKEN
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=l0_auth
      - POSTGRES_PASSWORD=postgres12345
      - POSTGRES_USERNAME=l0_auth_service
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres:
