

services:
  backend:
    build: auth
    ports:
      - 10502:10502
    environment:
      - POSTGRES_DB=example
      - DOPPLER_TOKEN
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=mypassword
    expose:
      - 5432
volumes:
  db-data:
networks:
  spring-postgres:
