services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build:
      context: .
      dockerfile: dev.dockerfile
      args:
        - JAR_FILE=target/*.jar
    ports:
      - 10502:10502
    environment:
      - POSTGRES_DB=l0_auth
      - DOPPLER_TOKEN


volumes:
  db-data:
