openapi: 3.0.1
info:
  title: Account Management
  description: TIKI's account management service —configure and provision access to
    the data platform
  license:
    name: MIT
    url: https://github.com/tiki/core-account-service/blob/main/LICENSE
  version: 2.9.20
servers:
- url: https://account.mytiki.com
paths:
  /api/latest/subscription:
    get:
      tags:
      - Managing Data Subscriptions
      summary: List Subscriptions
      description: Returns a filterable list of data subscriptions
      operationId: account-subscription-list
      security:
      - default:
        - account:admin
    post:
      tags:
      - Managing Data Subscriptions
      summary: Create Estimate
      description: Creates a new estimate for a data subscription
      operationId: account-subscription-estimate
      security:
      - default:
        - account:admin
  /api/latest/subscription/{subscription-id}/purchase:
    post:
      tags:
      - Managing Data Subscriptions
      summary: Purchase Subscription
      description: Converts an estimate into a paid data subscription.
      operationId: account-subscription-purchase
      security:
      - default:
        - account:admin
  /api/latest/provider:
    post:
      tags:
      - Managing Data Providers
      summary: Create Provider
      description: "Creates a new data provider, returning the configuration details"
      operationId: account-provider-create
      security:
      - default:
        - account:admin
  /api/latest/provider/{provider-id}/user:
    get:
      tags:
      - Managing End Users
      summary: List Addresses
      description: Returns all registered device addresses matching the criteria
      operationId: account-provider-user-get
      security:
      - default:
        - account:provider
    post:
      tags:
      - Managing End Users
      summary: Register Address
      description: Register a new device address for an end user
      operationId: account-provider-user-post
      security:
      - default:
        - account:provider
    delete:
      tags:
      - Managing End Users
      summary: Delete Addresses
      description: Permanently delete all device addresses matching the criteria
      operationId: account-provider-user-delete
      security:
      - default:
        - account:admin
  /api/latest/profile:
    get:
      tags:
      - Profile
      summary: Get Profile
      description: Returns your profile information
      operationId: account-profile-get
      security:
      - default:
        - account:admin
    post:
      tags:
      - Profile
      summary: Update Profile
      description: Update your profile information — see request body for modification
        options
      operationId: account-profile-post
      security:
      - default:
        - account:admin
    delete:
      tags:
      - Profile
      summary: Delete Account
      description: Permanently delete your account — requires email confirmation
      operationId: account-profile-delete
      security:
      - default:
        - account:admin
  /api/latest/cleanroom:
    get:
      tags:
      - Managing Cleanrooms
      summary: List Cleanrooms
      description: Returns the configuration details for a data cleanroom
      operationId: account-cleanroom-list
      security:
      - default:
        - account:admin
    post:
      tags:
      - Managing Cleanrooms
      summary: Create Cleanroom
      description: "Creates a new data cleanroom, returning the configuration details"
      operationId: account-cleanroom-create
      security:
      - default:
        - account:admin
  /api/latest/subscription/{subscription-id}:
    get:
      tags:
      - Managing Data Subscriptions
      summary: Get Subscription
      description: Returns the current status for a data subscription
      operationId: account-subscription-get
      security:
      - default:
        - account:admin
  /api/latest/provider/{provider-id}:
    get:
      tags:
      - Managing Data Providers
      summary: Get Provider
      description: Returns the configuration details for a data provider
      operationId: account-provider-get
      security:
      - default:
        - account:admin
    delete:
      tags:
      - Managing Data Providers
      summary: Delete Provider
      description: Permanently delete a data provider — stops publishing of new data.
      operationId: account-provider-delete
      security:
      - default:
        - account:admin
  /api/latest/cleanroom/{cleanroom-id}:
    get:
      tags:
      - Managing Cleanrooms
      summary: Get Cleanroom
      description: Returns the configuration details for a data cleanroom
      operationId: account-cleanroom-get
      security:
      - default:
        - account:admin
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer