openapi: 3.0.1
info:
  title: TIKI Account
  description: TIKI's account management service —configure and provision access to
    the data platform
  license:
    name: MIT
    url: https://github.com/tiki/tiki-account/blob/main/LICENSE
  version: 2.6.0
servers:
- url: https://mytiki.com/api/account
paths:
  /api/latest/provider:
    post:
      tags:
      - ""
      summary: Create App
      description: Create a new App
      operationId: account-app-create
      security:
      - oauth:
        - account:admin
  /api/latest/provider/{provider-id}:
    get:
      tags:
      - ""
      summary: Get App
      description: Retrieve the details about an App
      operationId: account-app-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - ""
      summary: Update App
      description: Update the details for an App
      operationId: account-app-update
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - ""
      summary: Delete App
      description: Permanently delete an App
      operationId: account-app-delete
      security:
      - oauth:
        - account:admin
  /api/latest/provider/{provider-id}/user:
    get:
      tags:
      - ""
      summary: Get Addresses
      description: Retrieve and filter registered addresses
      operationId: account-addr-reg-get
      security:
      - oauth:
        - account:provider
    post:
      tags:
      - ""
      summary: Register Address
      description: Register an end user address
      operationId: account-addr-reg-post
      security:
      - oauth:
        - account:provider
    delete:
      tags:
      - ""
      summary: Delete Addresses
      description: Delete registered addresses
      operationId: account-addr-reg-delete
      security:
      - oauth:
        - account:admin
  /api/latest/profile:
    get:
      tags:
      - ""
      summary: Get User
      description: Get the authorized user's profile
      operationId: account-user-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - ""
      summary: Update User
      description: Update the authorized User's profile
      operationId: account-user-post
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - ""
      summary: Delete User
      description: Delete the authorized user
      operationId: account-user-delete
      security:
      - oauth:
        - account:admin
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://mytiki.com/api/account/oauth/token
          refreshUrl: https://mytiki.com/api/account/oauth/token
          scopes:
            auth: this service
