openapi: 3.0.1
info:
  title: TIKI Account
  description: TIKI's account management service —configure and provision access to
    the data platform
  license:
    name: MIT
    url: https://github.com/tiki/tiki-account/blob/main/LICENSE
  version: 2.5.0
servers:
- url: https://mytiki.com/api/account
paths:
  /api/latest/user:
    get:
      tags:
      - ""
      summary: Get User
      description: Get the authorized user's profile
      operationId: account-user-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - ""
      summary: Update User
      description: Update the authorized User's profile
      operationId: account-user-post
      security:
      - oauth:
        - account:admin
  /api/latest/auth/token:
    post:
      tags:
      - ""
      summary: Grant Token
      description: Grant a new authorization token (with scope)
      operationId: account-oauth-token-post_1_1_1
  /api/latest/auth/revoke:
    post:
      tags:
      - ""
      summary: Revoke Token
      description: Revoke a Refresh token.
      operationId: account-oauth-revoke-post
  /api/latest/auth/otp:
    post:
      tags:
      - ""
      summary: Request OTP
      description: Start a one-time password (email) authorization flow
      operationId: account-otp-start-post
  /api/latest/app:
    post:
      tags:
      - ""
      summary: Create App
      description: Create a new App
      operationId: account-app-create
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}:
    get:
      tags:
      - ""
      summary: Get App
      description: Retrieve the details about an App
      operationId: account-app-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - ""
      summary: Update App
      description: Update the details for an App
      operationId: account-app-update
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - ""
      summary: Delete App
      description: Permanently delete an App
      operationId: account-app-delete
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}/key:
    get:
      tags:
      - ""
      summary: Get API Keys
      description: Retrieve the API Keys for an App
      operationId: account-api-keys-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - ""
      summary: Create API Key
      description: Create a new API Key for an App
      operationId: account-api-keys-create
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - ""
      summary: Delete Key
      description: Permanently revoke an API Key
      operationId: account-api-keys-delete
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}/address:
    get:
      tags:
      - ""
      summary: Get Addresses
      description: Retrieve and filter registered addresses
      operationId: account-addr-reg-get
      security:
      - oauth:
        - account:app
    post:
      tags:
      - ""
      summary: Register Address
      description: Register an end user address
      operationId: account-addr-reg-post
      security:
      - oauth:
        - account:app
    delete:
      tags:
      - ""
      summary: Delete Addresses
      description: Delete registered addresses
      operationId: account-addr-reg-delete
      security:
      - oauth:
        - account:admin
  /api/latest/org:
    get:
      tags:
      - ""
      summary: Get Org
      description: Retrieve the authorized User's Org details
      operationId: account-org-get
      security:
      - oauth:
        - account:admin
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://mytiki.com/api/account/oauth/token
          refreshUrl: https://mytiki.com/api/account/oauth/token
          scopes:
            auth: this service
