openapi: 3.0.1
info:
  title: Account
  description: Account management service —configure and provision access to the platform
  license:
    name: MIT
    url: https://github.com/tiki/core-account-service/blob/main/LICENSE
  version: 2.6.0
servers:
- url: https://account.mytiki.com
paths:
  /api/latest/user:
    get:
      tags:
      - User
      summary: Get User
      description: Get the authorized user's profile
      operationId: account-user-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - User
      summary: Update User
      description: Update the authorized User's profile
      operationId: account-user-post
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - User
      summary: Delete User
      description: Delete the authorized user
      operationId: account-user-delete
      security:
      - oauth:
        - account:admin
  /api/latest/app:
    post:
      tags:
      - App
      summary: Create App
      description: Create a new App
      operationId: account-app-create
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}:
    get:
      tags:
      - App
      summary: Get App
      description: Retrieve the details about an App
      operationId: account-app-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - App
      summary: Update App
      description: Update the details for an App
      operationId: account-app-update
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - App
      summary: Delete App
      description: Permanently delete an App
      operationId: account-app-delete
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}/key:
    get:
      tags:
      - App
      summary: Get API Keys
      description: Retrieve the API Keys for an App
      operationId: account-api-keys-get
      security:
      - oauth:
        - account:admin
    post:
      tags:
      - App
      summary: Create API Key
      description: Create a new API Key for an App
      operationId: account-api-keys-create
      security:
      - oauth:
        - account:admin
    delete:
      tags:
      - App
      summary: Delete Key
      description: Permanently revoke an API Key
      operationId: account-api-keys-delete
      security:
      - oauth:
        - account:admin
  /api/latest/app/{app-id}/address:
    get:
      tags:
      - User
      summary: Get Addresses
      description: Retrieve and filter registered addresses
      operationId: account-addr-reg-get
      security:
      - apiKey:
        - account:app
    post:
      tags:
      - User
      summary: Register Address
      description: Register an end user address
      operationId: account-addr-reg-post
      security:
      - apiKey:
        - account:app
components:
  securitySchemes:
    apiKey:
      type: apiKey
    oauth:
      type: oauth2
