AWSTemplateFormatVersion: '2010-09-09'
Description: Core Account EC2

Parameters:
  VpcId:
    Type: String
    Description: The id of the VPC to use.
  Subnets:
    Type: List<String>
    Description: List of public subnets for the load balancer.
  Certificate:
    Type: String
    Description: ARN of the SSL certificate.
  Port:
    Type: Number
    Description: Port number for the service.
    Default: 8228

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: core-account-service
      GroupDescription: Core Account Service
      Tags:
        - Key: Name
          Value: Core Account Service
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupName: core-account-service
        - IpProtocol: tcp
          FromPort: 8228
          ToPort: 8228
          SourceSecurityGroupName: core-account-service
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIpv6: ::/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: core-account-service
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets: !Ref Subnets

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Name: core-account-service
      Port: !Ref Port
      Protocol: HTTP
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      TargetType: ip

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref Certificate
      SslPolicy: ELBSecurityPolicy-TLS13-1-0-2021-06
      LoadBalancerArn: !GetAtt LoadBalancer.LoadBalancerArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !GetAtt TargetGroup.TargetGroupArn

Outputs:
  SecurityGroup:
    Description: Security group id
    Value: !GetAtt SecurityGroup.GroupId
  TargetGroup:
    Description: Target group arn
    Value: !GetAtt TargetGroup.TargetGroupArn
