AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Account GitHub deployment

Parameters:
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubDeployCoreAccountService"

Resources:
  Role:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-aws-github-role
        SemanticVersion: 0.0.3
      Parameters:
        GitHubOrg: tiki
        RepositoryName: core-account-service
        RoleName: !Ref RoleName

  Policy:
    Type: AWS::IAM::RolePolicy
    DependsOn: Role
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-account-*
              - !Sub arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action: cloudformation:ListStacks
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - arn:aws:s3:::mytiki-sam-deploy/*
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:DeleteRole
              - iam:TagRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/core-ocean-sar-*
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: "*"
          - Effect: Allow
            Action:
              - ecr:InitiateLayerUpload
              - ecr:CompleteLayerUpload
              - ecr:UploadLayerPart
              - ecr:PutImage
              - ecr:BatchCheckLayerAvailability
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/core-account-service
          - Effect: Allow
            Action:
              - ec2:DescribeSecurityGroups
            Resource: "*"
          - Effect: Allow
            Action:
              - ec2:CreateSecurityGroup
              - ec2:CreateTags
              - ec2:RevokeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AuthorizeSecurityGroupEgress
            Resource:
              - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/*
              - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*
          - Effect: Allow
            Action:
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetGroupAttributes
              - elasticloadbalancing:DescribeTargetHealth
              - elasticloadbalancing:DescribeTags
              - elasticloadbalancing:DescribeListeners
            Resource: "*"
          - Effect: Allow
            Action:
              - elasticloadbalancing:AddTags
              - elasticloadbalancing:CreateLoadBalancer
              - elasticloadbalancing:CreateTargetGroup
              - elasticloadbalancing:CreateListener
            Resource:
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener-rule/net/*/*/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener-rule/app/*/*/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/net/*/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/*/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:loadbalancer/app/*/*
              - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:loadbalancer/net/*/*
          - Effect: Allow
            Action:
              - rds:DescribeDBInstances
            Resource: "*"
          - Effect: Allow
            Action:
              - rds:DescribeDBInstances
            Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:*
          - Effect: Allow
            Action:
              - ecr:CreateRepository
            Resource: "*"
          - Effect: Allow
            Action:
              - ecr:DescribeRepositories
              - ecr:SetRepositoryPolicy
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/core-account-service
          - Effect: Allow
            Action:
              - ecs:DescribeClusters
              - ecs:CreateCluster
              - ecs:RegisterTaskDefinition
              - ecs:DescribeTaskDefinition
            Resource: "*"
          - Effect: Allow
            Action:
              - ecs:CreateService
              - ecs:DescribeServices
            Resource: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/*/*
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
