name: Version

on:
  pull_request:
    branches:
      - main

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Version:
    if: startsWith(github.head_ref, 'release/')
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'zulu'

      - name: Checkout PR
        id: getpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          export PR_BRANCH=$(git branch --show-current)
          echo "branch=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ steps.getpr.outputs.branch }}

      - name: Set Version
        run: |
          sed -i '0,/<version>*.*.*<\/version>/s//<version>${{ steps.semver.outputs.nextStrict }}<\/version>/' pom.xml

      - name: Commit Changes
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GH Action"
          git add pom.xml
          git add openapi.yaml
          git commit -m 'version bump'
          git push
